name: 'beimengyeyu@up2qn'
description: '上传文件到七牛'
author: 'beimengyeyu <me@beimengyeyu.com>'
branding:
  color: 'green'
  icon: 'arrow-up-circle'

inputs:
  bucket:
    description: '七牛云空间名称'
    required: true
  zone:
    description: '七牛云存储区域 如: 华南 华东 华北 北美 东南亚'
    required: true
  access_key:
    description: '到七牛云 个人中心 -> 密钥管理 获取 AccessKey，为确保您的空间安全，请使用 github 仓库 secrets 变量'
    required: true
  secret_key:
    description: '到七牛云 个人中心 -> 密钥管理 获取  SecretKey，为确保您的空间安全，请使用 github 仓库 secrets 变量'
    required: true
  local_dir:
    description: '本地要上传的文件夹'
    required: true
    default: 'dist'
  local_exclude:
    description: '本地要排除的文件'
  target_dir:
    description: '七牛云空间里的文件夹'
    default: '/'
  rpc_timeout:
    description: '超时时间'
    default: '120000'

runs:
  using: 'node12'
  main: 'dist/index.js'